In [1]:
import numpy as np
import math
import operator
import pandas as pd
import os
import time
from datetime import datetime
from time import mktime

from openpyxl import load_workbook

import matplotlib
import matplotlib.pyplot as plt

from matplotlib import style
#style.use('dark_background')
style.use('ggplot')

#import re
#import urllib
#path = "/home/juanma/Datos/owncloud_UPM/programacion/python/marcadores"
#url = "https://community.watsonanalytics.com/wp-content/uploads/2015/04/WA_Fn-UseC_-Sales-Win-Loss.csv"
#sales_data = pd.read_csv(url)
#data = pd.read_csv("iris.csv")
# data_marc_df = pd.read_excel('Data/Historia_pacientes.xlsx', header=51)
dfhist = pd.read_excel('Data/Historia clínica pacientes FJD.xlsx', header=51)
dfpac= pd.read_excel('Data/Excel 2 - Código paciente FJD.xlsx')
print(len(dfhist))
print(dfhist.columns)

C:\Users\juanm\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED


85
Index(['CODIGO PACIENTE', 'FECHA NAC', 'GENERO', 'MEDICO',
       'ANTECEDENTES FAMILIARES', 'CODIGO MUESTRA', 'FECHA MUESTRA',
       'ULTIMO SEGUIMIENTO', 'ESTADO', 'ESTADIO AL DX',
       ...
       'C3 2L POST', 'BIOL 2L', 'INICIO BIOL 2L', 'FINAL BIOL 2L',
       'CONCENTRACIÓN BIOL 2L', 'TOXICIDAD 2L', 'FECHA TOXICIDAD 2L',
       'REDUCCION DOSIS 2L', 'FECHA REDUCCION DOSIS 2L', 'EC2L'],
      dtype='object', length=136)


In [2]:
pacien_list0=dfpac['CODIGO PACIENTE']
pacien_list = []
for p in pacien_list0:
    if p not in pacien_list:
        pacien_list.append(p)
print(pacien_list)

['HJDP0001', 'HJDP0002', 'HJDP0003', 'HJDP0004', 'HJDP0005', 'HJDP0006', 'HJDP0007', 'HJDP0008', 'HJDP0009', 'HJDP0010', 'HJDP0011', 'HJDP0012', 'HJDP0013', 'HJDP0014', 'HJDP0015', 'HJDP0016', 'HJDP0017', 'HJDP0018', 'HJDP0019', 'HJDP0020', 'HJDP0021', 'HJDP0022', 'HJDP0023', 'HJDP0024', 'HJDP0025', 'HJDP0026', 'HJDP0027', 'HJDP0028', 'HJDP0029', 'HJDP0030', 'HJDP0031', 'HJDP9999', 'HJDP0032', 'HJDP0033', 'HJDP0034', 'HJDP0035', 'HJDP0036']


In [3]:
# filename0 = 'Data/paciente_HJDP0001_BD.xlsx'
# dfdata = pd.read_excel(filename0)
# dfdata.head()
dfdata = pd.DataFrame()
for pac in pacien_list:
    filename = 'Data/paciente_' + pac + '_BD.xlsx'
    print(filename)
    if os.path.isfile(filename):
        data0 = pd.read_excel(filename)
        print(data0.index.values)
        dfdata = pd.concat([dfdata,data0])
    else:
        print(filename,'no existe\n')
    
    
len(dfdata)

Data/paciente_HJDP0001_BD.xlsx
[0 1 2 3]
Data/paciente_HJDP0002_BD.xlsx
[0 1]
Data/paciente_HJDP0003_BD.xlsx
[0]
Data/paciente_HJDP0004_BD.xlsx
[0 1]
Data/paciente_HJDP0005_BD.xlsx
[0 1 2 3 4]
Data/paciente_HJDP0006_BD.xlsx
[0 1 2 3]
Data/paciente_HJDP0007_BD.xlsx
[0]
Data/paciente_HJDP0008_BD.xlsx
[0 1 2 3 4 5]
Data/paciente_HJDP0009_BD.xlsx
[0 1 2]
Data/paciente_HJDP0010_BD.xlsx
[0 1 2 3]
Data/paciente_HJDP0011_BD.xlsx
[0 1]
Data/paciente_HJDP0012_BD.xlsx
[0 1 2 3]
Data/paciente_HJDP0013_BD.xlsx
[0 1]
Data/paciente_HJDP0014_BD.xlsx
[0 1]
Data/paciente_HJDP0015_BD.xlsx
[0 1 2]
Data/paciente_HJDP0016_BD.xlsx
[0 1 2]
Data/paciente_HJDP0017_BD.xlsx
[0 1 2 3]
Data/paciente_HJDP0018_BD.xlsx
[0 1]
Data/paciente_HJDP0019_BD.xlsx
[0 1 2]
Data/paciente_HJDP0020_BD.xlsx
[0 1 2]
Data/paciente_HJDP0021_BD.xlsx
[0 1 2 3]
Data/paciente_HJDP0022_BD.xlsx
[0 1]
Data/paciente_HJDP0023_BD.xlsx
[0 1]
Data/paciente_HJDP0024_BD.xlsx
[0 1]
Data/paciente_HJDP0025_BD.xlsx
[0 1]
Data/paciente_HJDP0026_BD.xlsx


100

In [4]:
dfdata.set_index('id_muestra', inplace=True)

In [9]:
# dfdata

In [5]:
dfhist.set_index('CODIGO MUESTRA', inplace=True)

In [6]:
dfhist.index

Index(['HJD0001', 'HJD0002', 'HJD0003', 'HJD0004', 'HJD0005', 'HJD0006',
       'HJD0007', 'HJD0008', 'HJD0009', 'HJD0010', 'HJD0011', 'HJD0012',
       'HJD0013', 'HJD0014', 'HJD0015', 'HJD0016', 'HJD0017', 'HJD0018',
       'HJD0019', 'HJD0020', 'HJD0021', 'HJD0022', 'HJD0023', 'HJD0024',
       'HJD0025', 'HJD0026', 'HJD0027', 'HJD0028', 'HJD0029', 'HJD0030',
       'HJD0031', 'HJD0032', 'HJD0033', 'HJD0034', 'HJD0035', 'HJD0036',
       'HJD0037', 'HJD0038', 'HJD0039', 'HJD0040', 'HJD0041', 'HJD0042',
       'HJD0043', 'HJD0044', 'HJD0045', 'HJD0046', 'HJD0047', 'HJD0048',
       'HJD0049', 'HJD0050', 'HJD0051', 'HJD0052', 'HJD0054', 'HJD0055',
       'HJD0056', 'HJD0057', 'HJD0058', 'HJD0059', 'HJD0060', 'HJD0061',
       'HJD0062', 'HJD0063', 'HJD0064', 'HJD0065', 'HJD0066', 'HJD0067',
       'HJD0068', 'HJD0073', 'HJD0074', 'HJD0075', 'HJD0076', 'HJD0077',
       'HJD0078', 'HJD0079', 'HJD0080', 'HJD0081', 'HJD0082', 'HJD0083',
       'HJD0084', 'HJD0085', 'HJD0086', 'HJD0093', 

In [12]:
dfhist = dfhist[~dfhist.index.duplicated(keep='first')]
dfhist.columns
print(dfhist.index.values)
print(len(dfhist))

['HJD0001' 'HJD0002' 'HJD0003' 'HJD0004' 'HJD0005' 'HJD0006' 'HJD0007'
 'HJD0008' 'HJD0009' 'HJD0010' 'HJD0011' 'HJD0012' 'HJD0013' 'HJD0014'
 'HJD0015' 'HJD0016' 'HJD0017' 'HJD0018' 'HJD0019' 'HJD0020' 'HJD0021'
 'HJD0022' 'HJD0023' 'HJD0024' 'HJD0025' 'HJD0026' 'HJD0027' 'HJD0028'
 'HJD0029' 'HJD0030' 'HJD0031' 'HJD0032' 'HJD0033' 'HJD0034' 'HJD0035'
 'HJD0036' 'HJD0037' 'HJD0038' 'HJD0039' 'HJD0040' 'HJD0041' 'HJD0042'
 'HJD0043' 'HJD0044' 'HJD0045' 'HJD0046' 'HJD0047' 'HJD0048' 'HJD0049'
 'HJD0050' 'HJD0051' 'HJD0052' 'HJD0054' 'HJD0055' 'HJD0056' 'HJD0057'
 'HJD0058' 'HJD0059' 'HJD0060' 'HJD0061' 'HJD0062' 'HJD0063' 'HJD0064'
 'HJD0065' 'HJD0066' 'HJD0067' 'HJD0068' 'HJD0073' 'HJD0074' 'HJD0075'
 'HJD0076' 'HJD0077' 'HJD0078' 'HJD0079' 'HJD0080' 'HJD0081' 'HJD0082'
 'HJD0083' 'HJD0084' 'HJD0085' 'HJD0086' 'HJD0093' 'HJD0094' 'HJD0095'
 'HJD0096']
85


## Es un rollo el manejo con fechas, aquí está su lectura y cómo quitar las vacías

In [7]:
nat = pd.NaT
dfhist['FECHA MUESTRA'] = pd.to_datetime(dfhist['FECHA MUESTRA'], infer_datetime_format=True)

# dfhist.loc[dfhist['FECHA MUESTRA']=='NaT','FECHA DX 1L']=''
dfhist['FECHA DX 1L'] = dfhist['FECHA DX 1L'].astype(str)
dfhist.loc[dfhist['FECHA DX 1L']=='NaT','FECHA DX 1L']=''

dfhist['FECHA DX 2L'] = dfhist['FECHA DX 2L'].astype(str)
dfhist.loc[dfhist['FECHA DX 2L']=='NaT','FECHA DX 2L']=''
# dfhist['FECHA DX 1L'] = pd.to_datetime(dfhist['FECHA DX 1L'], infer_datetime_format=True).dt.date

pacientes_recaida1=[]
pacientes_recaida2=[]

for p in pacien_list:
    print('\n\nPaciente:',p)
    for m in dfhist.index.values:
#         print(m, 'FECHA DX 1L:', dfhist.loc[m, 'FECHA DX 1L'], type(dfhist.loc[m, 'FECHA DX 1L']))
    
        if (dfhist.loc[m, 'FECHA DX 1L']!='') and (dfhist.loc[m,'CODIGO PACIENTE']==p) and (p not in pacientes_recaida1) :
            print('encuentro recaída en muestra:',m)
            m_p = list(dfhist['CODIGO PACIENTE']==p)
            m_p_rec = [i for i in range(len(m_p)) if m_p[i]]
            print('lista de otras muestras del paciente',p,':',m_p_rec)
            for i in m_p_rec:                
                m0 = dfhist.index[i]    
                ### .days para pasarlo a type(int)
                dfhist.loc[m0, 'FECHA DX 1L'] = dfhist.loc[m, 'FECHA DX 1L']
                dfhist.loc[m0, 'T_recaida1'] = (datetime.strptime(dfhist.loc[m,'FECHA DX 1L'], '%Y-%m-%d') - dfhist.loc[m0,'FECHA MUESTRA']).days
                print('paciente:',dfhist.loc[m0,'CODIGO PACIENTE'],'muestra:',m0,'t=',dfhist.loc[m0,'FECHA MUESTRA'],'tiempo 1ª recaída:', dfhist.loc[m, 'FECHA DX 1L'], 'días:', dfhist.loc[m0,'T_recaida1'])
            if p not in pacientes_recaida1:
                pacientes_recaida1.append(p)
                
print(pacientes_recaida1)
print('\n\nAhora calculamos tiempos para la 2ª recaída')

for p in pacien_list:
    print('\n\nPaciente:',p)
    for m in dfhist.index.values:
    
        if (dfhist.loc[m, 'FECHA DX 2L']!='') and (dfhist.loc[m,'CODIGO PACIENTE']==p) and (p not in pacientes_recaida2) :
            print('encuentro 2ª recaída en muestra:',m, 'en t=',dfhist.loc[m, 'FECHA DX 2L'])
            m_p = list(dfhist['CODIGO PACIENTE']==p)
            m_p_rec = [i for i in range(len(m_p)) if m_p[i]]
            print('lista de otras muestras del paciente',p,':',m_p_rec)
            for i in m_p_rec:                
                m0 = dfhist.index[i]    
                ### .days para pasarlo a type(int)
                dfhist.loc[m0, 'FECHA DX 2L'] = dfhist.loc[m, 'FECHA DX 2L']
                t1 = datetime.strptime(dfhist.loc[m,'FECHA DX 1L'], '%Y-%m-%d')
                t2 = datetime.strptime(dfhist.loc[m,'FECHA DX 2L'], '%Y-%m-%d')
                t = dfhist.loc[m0,'FECHA MUESTRA']
                print(t1,t2,'t:',t)
                if t>t1:
                    dfhist.loc[m0, 'T_recaida2'] = (t2 - t).days
                    print('paciente:',dfhist.loc[m0,'CODIGO PACIENTE'],'muestra:',m0,'t=',dfhist.loc[m0,'FECHA MUESTRA'],'t_1ª recaída:', t1,'t_2ª recaída:', t2, 'días:', dfhist.loc[m0,'T_recaida2'])
            if p not in pacientes_recaida2:
                pacientes_recaida2.append(p)

print(pacientes_recaida1)



Paciente: HJDP0001
encuentro recaída en muestra: HJD0083
lista de otras muestras del paciente HJDP0001 : [0, 22, 77, 80]
paciente: HJDP0001 muestra: HJD0001 t= 2021-02-17 00:00:00 tiempo 1ª recaída: 2022-02-04 días: 352.0
paciente: HJDP0001 muestra: HJD0023 t= 2021-06-15 00:00:00 tiempo 1ª recaída: 2022-02-04 días: 234.0
paciente: HJDP0001 muestra: HJD0083 t= 2022-02-08 00:00:00 tiempo 1ª recaída: 2022-02-04 días: -4.0
paciente: HJDP0001 muestra: HJD0086 t= 2022-02-22 00:00:00 tiempo 1ª recaída: 2022-02-04 días: -18.0


Paciente: HJDP0002


Paciente: HJDP0003


Paciente: HJDP0004


Paciente: HJDP0005
encuentro recaída en muestra: HJD0005
lista de otras muestras del paciente HJDP0005 : [4, 9, 24, 62, 84]
paciente: HJDP0005 muestra: HJD0005 t= 2021-02-18 00:00:00 tiempo 1ª recaída: 2021-01-15 días: -34.0
paciente: HJDP0005 muestra: HJD0010 t= 2021-03-15 00:00:00 tiempo 1ª recaída: 2021-01-15 días: -59.0
paciente: HJDP0005 muestra: HJD0025 t= 2021-06-21 00:00:00 tiempo 1ª recaída: 2021-

<ipython-input-7-d569cf29dbf1>:2: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  dfhist['FECHA MUESTRA'] = pd.to_datetime(dfhist['FECHA MUESTRA'], infer_datetime_format=True)


In [14]:
dfhist.head(15)

CODIGO PACIENTE  FECHA NAC     GENERO  \
CODIGO MUESTRA                                         
HJD0001               HJDP0001 1955-07-31  Masculino   
HJD0002               HJDP0002 1943-08-11  Masculino   
HJD0003               HJDP0003 1960-03-11   Femenino   
HJD0004               HJDP0004 1954-09-27   Femenino   
HJD0005               HJDP0005 1965-01-25  Masculino   
HJD0006               HJDP0006 1976-03-07  Masculino   
HJD0007               HJDP0007 1951-12-24  Masculino   
HJD0008               HJDP0008 1943-12-15  Masculino   
HJD0009               HJDP0009 1947-07-01  Masculino   
HJD0010               HJDP0005 1965-01-25  Masculino   
HJD0011               HJDP0010 1963-12-25  Masculino   
HJD0012               HJDP0011 1963-06-11  Masculino   
HJD0013               HJDP0012 1953-06-25   Femenino   
HJD0014               HJDP0013 1956-12-02   Femenino   
HJD0015               HJDP0014 1969-10-13  Masculino   

                                  MEDICO ANTECEDENTES FAMILIARES  \
CODIGO MUESTRA                                                     
HJD0001                  EVA RUIZ HISPAN             Desconocido   
HJD0002         CRISTINA CARAMES SANCHEZ             Desconocido   
HJD0003         CRISTINA CARAMES SANCHEZ                      No   
HJD0004         CRISTINA CARAMES SANCHEZ                      No   
HJD0005                  EVA RUIZ HISPAN                      Si   
HJD0006                  EVA RUIZ HISPAN                      Si   
HJD0007                  EVA RUIZ HISPAN                      Si   
HJD0008                  EVA RUIZ HISPAN             Desconocido   
HJD0009         CRISTINA CARAMES SANCHEZ                      No   
HJD0010                  EVA RUIZ HISPAN                      Si   
HJD0011         CRISTINA CARAMES SANCHEZ             Desconocido   
HJD0012         CRISTINA CARAMES SANCHEZ             Desconocido   
HJD0013         MANUEL PEDREGAL TRUJILLO                      Si   
HJD0014         CRISTINA CARAMES SANCHEZ             Desconocido   
HJD0015         CRISTINA CARAMES SANCHEZ             Desconocido   

               FECHA MUESTRA ULTIMO SEGUIMIENTO       ESTADO ESTADIO AL DX  \
CODIGO MUESTRA                                                               
HJD0001           2021-02-17         2021-02-17  Tratamiento           III   
HJD0002           2021-02-17         2021-02-17  Tratamiento           III   
HJD0003           2021-02-18         2021-02-18         Alta             I   
HJD0004           2021-02-18         2021-02-18         Alta             I   
HJD0005           2021-02-18         2021-02-18  Tratamiento            IV   
HJD0006           2021-02-23         2021-02-23  Tratamiento            II   
HJD0007           2021-03-15         2021-03-15  Tratamiento            IV   
HJD0008           2021-03-15         2021-03-15  Tratamiento           III   
HJD0009           2021-03-15         2021-03-15  Tratamiento           III   
HJD0010           2021-03-15         2021-03-15  Tratamiento            IV   
HJD0011           2021-03-22         2021-03-22  Tratamiento             I   
HJD0012           2021-03-22         2021-03-22  Tratamiento            IV   
HJD0013           2021-05-10         2021-05-10  Tratamiento           III   
HJD0014           2021-05-10         2021-05-10  Tratamiento           III   
HJD0015           2021-05-12         2021-05-12   Revisiones            II   

                         FUMADOR  ...  INICIO BIOL 2L  FINAL BIOL 2L  \
CODIGO MUESTRA                    ...                                  
HJD0001         Fumador expuesto  ...             NaT            NaN   
HJD0002            Nunca Fumador  ...             NaT            NaN   
HJD0003           Fumador activo  ...             NaT            NaN   
HJD0004            Nunca Fumador  ...             NaT            NaN   
HJD0005           Fumador activo  ...             NaT            NaN   
HJD0006            Nunca Fumador  ...             NaT            NaN   
HJ

In [8]:
dfhist['FECHA DX 1L']

CODIGO MUESTRA
HJD0001    2022-02-04
HJD0002              
HJD0003              
HJD0004              
HJD0005    2021-01-15
              ...    
HJD0086    2022-02-04
HJD0093              
HJD0094              
HJD0095              
HJD0096    2021-01-15
Name: FECHA DX 1L, Length: 85, dtype: object

In [9]:
dfhist.loc[dfhist['CEA']=='Normal', 'CEA']= 0
dfhist.loc[dfhist['CEA']=='Anormal', 'CEA']= 1
dfhist.loc[dfhist['C19-9']=='Normal', 'C19-9']= 0
dfhist.loc[dfhist['C19-9']=='Anormal', 'C19-9']= 1

In [10]:
now = pd.Timestamp('01-09-2023')

dfhist['FECHA NAC'] = pd.to_datetime(dfhist['FECHA NAC'], format='%m%d%y')    # 1
#historia2_df['FECHA_NAC'] = historia2_df['FECHA_NAC'].where(historia2_df['FECHA_NAC'] < now, historia2_df['FECHA'] -  np.timedelta64(100, 'Y'))   # 2
dfhist['EDAD'] = (now - dfhist['FECHA NAC'])
dfhist['EDAD']= (dfhist['EDAD']/ np.timedelta64(1, 'Y')).astype('int')

In [11]:
dfhist['FECHA MUESTRA'] = dfhist['FECHA MUESTRA'].astype(str)

In [13]:
columns_save=['CODIGO PACIENTE','FECHA MUESTRA','FECHA DX 1L','FECHA DX 2L','T_recaida1','T_recaida2','CEA', 'C19-9','EDAD',]
df_save = dfhist[columns_save]
df_save.to_excel('Data/Recaidas_FJD.xlsx')

<ipython-input-13-8ab4d675a3a4>:3: UserWarning: Pandas requires version '1.4.3' or newer of 'xlsxwriter' (version '1.3.7' currently installed).
  df_save.to_excel('Data/Recaidas_FJD.xlsx')
